### ISSUE TITLE
Grade Comments

### ISSUE THREAD

**Issue by andrewclavin** [TheLuomamr/Pyschic-game.github.io#1]
Site looks great and code is clean and organized. Some slight inconsistencies in your indentation in javascript to be careful of. Also don't you <br> tags to get space, they have a specific meaning to break text that doesn't already cause a break, for the spacing use margin or padding, probably margin in your case. Lastly, at the end of your css there is a strange lone double quote. As far as the user experience goes you might want to think of more of a signal that the guess was correct. Keep up the good work!

**Comment by TheLuomamr** [comment]
Thanks for the feedback Andrew, Much appreciated.
